### ISSUE TITLE
issue with running test generator with beamng

### ISSUE THREAD

**Issue by SashaSaw** [ADS-Testing/cps-tool-competition#1]
when i use:
python competition.py --time-budget 100 --executor beamng --map-size 200 --module-name sample_test_generators.one_test_generator --class-name OneTestGenerator

my output is:
2023-11-08 00:09:36,688 INFO     Started test generation
2023-11-08 00:09:36,688 INFO     Try to import OneTestGenerator from sample_test_generators.one_test_generator
2023-11-08 00:09:36,692 INFO     Outputting results to C:\cps-tool-competition\results\sample_test_generators.one_test_generator_OneTestGenerator_169940217669.0
2023-11-08 00:09:36,787 INFO     No OpenGL_accelerate module loaded: No module named 'OpenGL_accelerate'
2023-11-08 00:09:36,992 INFO     Using NT-specific GLUT calls with exit callbacks
2023-11-08 00:09:37,004 ERROR    Uncaught exception:
Traceback (most recent call last):
  File "C:\cps-tool-competition\competition.py", line 394, in <module>
    generate()
  File "C:\Users\sawsa\AppData\Local\Programs\Python\Python39\.venv\lib\site-packages\click\core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "C:\Users\sawsa\AppData\Local\Programs\Python\Python39\.venv\lib\site-packages\click\core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "C:\cps-tool-competition\competition.py", line 92, in invoke
    super(CommandOptionRequiredClass, self).invoke(ctx)
  File "C:\Users\sawsa\AppData\Local\Programs\Python\Python39\.venv\lib\site-packages\click\core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "C:\Users\sawsa\AppData\Local\Programs\Python\Python39\.venv\lib\site-packages\click\core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "C:\Users\sawsa\AppData\Local\Programs\Python\Python39\.venv\lib\site-packages\click\decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "C:\cps-tool-competition\competition.py", line 358, in generate
    the_executor = BeamngExecutor(result_folder, map_size,
  File "C:\cps-tool-competition\code_pipeline\beamng_executor.py", line 41, in __init__
    assert self.beamng_user is not None, "Please provide a --beamng-user folder"
AssertionError: Please provide a --beamng-user folder

what do i do how do i provide a beamng user folder?? (the simulator works fine when using mock executor)

**Comment by donghwan-shin** [comment]
This is related to the code below:
https://github.com/ADS-Testing/cps-tool-competition/blob/a185a047d66cc8c78656a1f2717686a347a2c0ee/competition.py#L257-L264

Assuming you have BeamNG installed under `C:\BeamNG.tech\`, you can do the following for `--beamng-home` by changing the `default` value for the parameter:
```python
@click.option('--beamng-home', required=False, default='C:\\BeamNG.tech', type=click.Path(exists=True),
              show_default='None',
              help="Customize BeamNG executor by specifying the home of the simulator.")
```

Similarly, you should make a beamng user folder, such as `C:\BeamNG-user`, and update the following for `--beamng-user`: 
```python
@click.option('--beamng-user', required=False, default='C:\\BeamNG-user', type=click.Path(exists=True),
              show_default='Currently Active User (~/BeamNG.tech/)',
              help="Customize BeamNG executor by specifying the location of the folder "
                   "where levels, props, and other BeamNG-related data will be copied."
                   "** Use this to avoid spaces in URL/PATHS! **")
```

**Comment by donghwan-shin** [comment]
This is copied from [Install.md](https://github.com/ADS-Testing/cps-tool-competition/blob/main/documentation/INSTALL.md#beamng-simulator) 

> Installing BeamNG.tech is as simple as extracting the files to a target folder in your system (e.g., C:\BeamNG.tech.v0.26.2.0). We call this folder <BEAMNG_HOME>. Additionally you need to create another folder (e.g., C:\BeamNG.tech.v0.26.2.0_userpath) that will act as BeamNG.tech working dir. BeamNG.tech will copy in this directory the levels and its cache. We call this folder <BEAMNG_USER>.

**Comment by donghwan-shin** [comment]
@SashaSaw If you are okay with the answer, can we close this issue?

**Comment by SashaSaw** [comment]
Oh yeah it’s working fine now
